data:
  type: datasets.single_shape_sdf_datasets
  num_workers: 4
  path: your_shape_sdf.npy # place holder
  train:
    length: 10000
    batch_size: 10
    num_sample_points: 10000
  val:
    length: 50
    batch_size: 10
    num_sample_points: 10000
input:
  point_path: balken.csv  
  net_path: /home/weidemaier/New Network/NFGP/logs/create_neural_fields_data.path=-home-weidemaier-NFGP-sphere2.npy_2024-Sep-11-12-14-57
  far_net: /home/weidemaier/New Network/NFGP/logs/create_neural_fields_data.path=-home-weidemaier-NFGP-sphere2.npy_2024-Sep-23-10-14-31  
  parameters:
    epsilon: 0.001
    tau: 0.01
    eta: 5
    near_cut_off: 15
    far_cut_off: 0.5
    inner_radius: 0.01
    bs: 1000
viz:
  log_freq: 10
  viz_freq: 100000
  save_freq: 1
  val_freq: 1

trainer:
  type: trainers.heat_trainer #heat_trainer  #w_normf_trainer
  epochs: 100
  seed: 100
  ndf_loss_weight: 0.
  sdf_loss_weight: 1.
  grad_norm_weight: 1e-2
  grad_norm_num_points: 10000
  opt:
    type: 'adam'
    lr: 1e-4 
    beta1: 0.9
    beta2: 0.999
    momentum: 0.9  # for SGD
    weight_decay: 0.
    scheduler: adaptive #adaptive #exponential #linear
    step_epoch: 200

models:
  decoder:
    type: models.siren_mlp #siren_mlp #linear_net
    trainer: w_normf_trainer
    dim: 3
    out_dim: 1
    hidden_size: 128 #256 #512 
    n_blocks: 4 #6
    z_dim: 256 #128
