data:
  type: datasets.single_shape_sdf_datasets
  num_workers: 4
  path: your_shape_sdf.npy # place holder
  train:
    length: 10000
    batch_size: 10000
    num_sample_points: 1000
  val:
    length: 50
    batch_size: 10000
    num_sample_points: 10000

viz:
  log_freq: 10
  viz_freq: 100000
  save_freq: 1
  val_freq: 1
input:
  parameters:
    normalize: no #"normalize"
    Neural_input_function: ""
    Surface_net: /home/weidemaier/HeatSDF/logs/NeuralSDFs_2025-Apr-16-16-04-15
    Neural_input_function: "None"

trainer:
  type: trainers.SurfaceEigenvalues
  epochs: 50
  seed: 100
  ndf_loss_weight: 0.
  sdf_loss_weight: 1.
  grad_norm_weight: 1e-2
  grad_norm_num_points: 10000
  opt:
    type: 'adam'
    lr: 0.00001 #0.0001
    beta1: 0.9
    beta2: 0.999
    momentum: 0.9  # for SGD
    weight_decay: 0.
    scheduler: adaptive #step #adaptive
    step_epoch: 8
models: !!python/object:argparse.Namespace
  decoder: !!python/object:argparse.Namespace
    dim: 3
    hidden_size: 256
    n_blocks: 4
    out_dim: 1
    type: models.siren_mlp

models:
  decoder:
    arch: [150,'elu', 150,'elu', 150,'elu', 150,'elu']
    approach: "band"
    bc: ["no", "comp_FEM"] #"simpl_sup"
    edge_l: 1
    force: ["circ", 1]
    lapl: true
    band_width: 0.5
    dim: 3
    out_dim: 1
    type: trainers.Points2SDF


